/**
 * @brief Timer control registers
 */

#include "registers/helpers.h"

#pragma once


#define TIM_2_BASE 0x40000000
#define TIM_3_BASE 0x40000400
#define TIM_4_BASE 0x40000800

#define TIM_CR1_OFFSET   0x00000000
#define TIM_CR2_OFFSET   0x00000004
#define TIM_SMCR_OFFSET  0x00000008
#define TIM_DIER_OFFSET  0x0000000C
#define TIM_SR_OFFSET    0x00000010
#define TIM_EGR_OFFSET   0x00000014
#define TIM_CCMR1_OFFSET 0x00000018
#define TIM_CCMR2_OFFSET 0x0000001C
#define TIM_CCER_OFFSET  0x00000020
#define TIM_CNT_OFFSET   0x00000024
#define TIM_PSC_OFFSET   0x00000028
#define TIM_ARR_OFFSET   0x0000002C
#define TIM_CCR1_OFFSET  0x00000034
#define TIM_CCR2_OFFSET  0x00000038
#define TIM_CCR3_OFFSET  0x0000003C
#define TIM_CCR4_OFFSET  0x00000040
#define TIM_DCR_OFFSET   0x00000048
#define TIM_DMAR_OFFSET  0x0000004C
#define TIM_OR1_OFFSET   0x00000050
#define TIM_AF1_OFFSET   0x00000060
#define TIM_TISEL_OFFSET 0x00000068


#define TIM_2_CR1   REGISTER(TIM_2_BASE + TIM_CR1_OFFSET)
#define TIM_2_CR2   REGISTER(TIM_2_BASE + TIM_CR2_OFFSET)
#define TIM_2_SMCR  REGISTER(TIM_2_BASE + TIM_SMCR_OFFSET)
#define TIM_2_DIER  REGISTER(TIM_2_BASE + TIM_DIER_OFFSET)
#define TIM_2_SR    REGISTER(TIM_2_BASE + TIM_SR_OFFSET)
#define TIM_2_EGR   REGISTER(TIM_2_BASE + TIM_EGR_OFFSET)
#define TIM_2_CCMR1 REGISTER(TIM_2_BASE + TIM_CCMR1_OFFSET)
#define TIM_2_CCMR2 REGISTER(TIM_2_BASE + TIM_CCMR2_OFFSET)
#define TIM_2_CCER  REGISTER(TIM_2_BASE + TIM_CCER_OFFSET)
#define TIM_2_CNT   REGISTER(TIM_2_BASE + TIM_CNT_OFFSET)
#define TIM_2_PSC   REGISTER(TIM_2_BASE + TIM_PSC_OFFSET)
#define TIM_2_ARR   REGISTER(TIM_2_BASE + TIM_ARR_OFFSET)
#define TIM_2_CCR1  REGISTER(TIM_2_BASE + TIM_CCR1_OFFSET)
#define TIM_2_CCR2  REGISTER(TIM_2_BASE + TIM_CCR2_OFFSET)
#define TIM_2_CCR3  REGISTER(TIM_2_BASE + TIM_CCR3_OFFSET)
#define TIM_2_CCR4  REGISTER(TIM_2_BASE + TIM_CCR4_OFFSET)
#define TIM_2_DCR   REGISTER(TIM_2_BASE + TIM_DCR_OFFSET)
#define TIM_2_DMAR  REGISTER(TIM_2_BASE + TIM_DMAR_OFFSET)
#define TIM_2_OR1   REGISTER(TIM_2_BASE + TIM_OR1_OFFSET)
#define TIM_2_AF1   REGISTER(TIM_2_BASE + TIM_AF1_OFFSET)
#define TIM_2_TISEL REGISTER(TIM_2_BASE + TIM_TISEL_OFFSET)


#define TIM_3_CR1   REGISTER(TIM_3_BASE + TIM_CR1_OFFSET)
#define TIM_3_CR2   REGISTER(TIM_3_BASE + TIM_CR2_OFFSET)
#define TIM_3_SMCR  REGISTER(TIM_3_BASE + TIM_SMCR_OFFSET)
#define TIM_3_DIER  REGISTER(TIM_3_BASE + TIM_DIER_OFFSET)
#define TIM_3_SR    REGISTER(TIM_3_BASE + TIM_SR_OFFSET)
#define TIM_3_EGR   REGISTER(TIM_3_BASE + TIM_EGR_OFFSET)
#define TIM_3_CCMR1 REGISTER(TIM_3_BASE + TIM_CCMR1_OFFSET)
#define TIM_3_CCMR2 REGISTER(TIM_3_BASE + TIM_CCMR2_OFFSET)
#define TIM_3_CCER  REGISTER(TIM_3_BASE + TIM_CCER_OFFSET)
#define TIM_3_CNT   REGISTER(TIM_3_BASE + TIM_CNT_OFFSET)
#define TIM_3_PSC   REGISTER(TIM_3_BASE + TIM_PSC_OFFSET)
#define TIM_3_ARR   REGISTER(TIM_3_BASE + TIM_ARR_OFFSET)
#define TIM_3_CCR1  REGISTER(TIM_3_BASE + TIM_CCR1_OFFSET)
#define TIM_3_CCR2  REGISTER(TIM_3_BASE + TIM_CCR2_OFFSET)
#define TIM_3_CCR3  REGISTER(TIM_3_BASE + TIM_CCR3_OFFSET)
#define TIM_3_CCR4  REGISTER(TIM_3_BASE + TIM_CCR4_OFFSET)
#define TIM_3_DCR   REGISTER(TIM_3_BASE + TIM_DCR_OFFSET)
#define TIM_3_DMAR  REGISTER(TIM_3_BASE + TIM_DMAR_OFFSET)
#define TIM_3_OR1   REGISTER(TIM_3_BASE + TIM_OR1_OFFSET)
#define TIM_3_AF1   REGISTER(TIM_3_BASE + TIM_AF1_OFFSET)
#define TIM_3_TISEL REGISTER(TIM_3_BASE + TIM_TISEL_OFFSET)


#define TIM_4_CR1   REGISTER(TIM_4_BASE + TIM_CR1_OFFSET)
#define TIM_4_CR2   REGISTER(TIM_4_BASE + TIM_CR2_OFFSET)
#define TIM_4_SMCR  REGISTER(TIM_4_BASE + TIM_SMCR_OFFSET)
#define TIM_4_DIER  REGISTER(TIM_4_BASE + TIM_DIER_OFFSET)
#define TIM_4_SR    REGISTER(TIM_4_BASE + TIM_SR_OFFSET)
#define TIM_4_EGR   REGISTER(TIM_4_BASE + TIM_EGR_OFFSET)
#define TIM_4_CCMR1 REGISTER(TIM_4_BASE + TIM_CCMR1_OFFSET)
#define TIM_4_CCMR2 REGISTER(TIM_4_BASE + TIM_CCMR2_OFFSET)
#define TIM_4_CCER  REGISTER(TIM_4_BASE + TIM_CCER_OFFSET)
#define TIM_4_CNT   REGISTER(TIM_4_BASE + TIM_CNT_OFFSET)
#define TIM_4_PSC   REGISTER(TIM_4_BASE + TIM_PSC_OFFSET)
#define TIM_4_ARR   REGISTER(TIM_4_BASE + TIM_ARR_OFFSET)
#define TIM_4_CCR1  REGISTER(TIM_4_BASE + TIM_CCR1_OFFSET)
#define TIM_4_CCR2  REGISTER(TIM_4_BASE + TIM_CCR2_OFFSET)
#define TIM_4_CCR3  REGISTER(TIM_4_BASE + TIM_CCR3_OFFSET)
#define TIM_4_CCR4  REGISTER(TIM_4_BASE + TIM_CCR4_OFFSET)
#define TIM_4_DCR   REGISTER(TIM_4_BASE + TIM_DCR_OFFSET)
#define TIM_4_DMAR  REGISTER(TIM_4_BASE + TIM_DMAR_OFFSET)
#define TIM_4_OR1   REGISTER(TIM_4_BASE + TIM_OR1_OFFSET)
#define TIM_4_AF1   REGISTER(TIM_4_BASE + TIM_AF1_OFFSET)
#define TIM_4_TISEL REGISTER(TIM_4_BASE + TIM_TISEL_OFFSET)

